/*
  Generated by atdts from type definitions in 'trace.atd'.

  Type-safe translations from/to JSON

  For each type 'Foo', there is a pair of functions:
  - 'writeFoo': convert a 'Foo' value into a JSON-compatible value.
  - 'readFoo': convert a JSON-compatible value into a TypeScript value
    of type 'Foo'.
*/

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */

export type Item = {
  step: number /*int*/;
  kind: Kind[];
  goal_id: number /*int*/;
  runtime_id: number /*int*/;
  name: string;
  payload: string[];
}

export type Kind =
| { kind: 'Start' }
| { kind: 'Info' }
| { kind: 'Stop'; value: Stop }
| { kind: 'Meta' }

export type Stop = {
  cause: string;
  time: number;
}

export type RawTrace = Item[]

export function writeItem(x: Item, context: any = x): any {
  return {
    'step': _atd_write_required_field('Item', 'step', _atd_write_int, x.step, x),
    'kind': _atd_write_required_field('Item', 'kind', _atd_write_array(writeKind), x.kind, x),
    'goal_id': _atd_write_required_field('Item', 'goal_id', _atd_write_int, x.goal_id, x),
    'runtime_id': _atd_write_required_field('Item', 'runtime_id', _atd_write_int, x.runtime_id, x),
    'name': _atd_write_required_field('Item', 'name', _atd_write_string, x.name, x),
    'payload': _atd_write_required_field('Item', 'payload', _atd_write_array(_atd_write_string), x.payload, x),
  };
}

export function readItem(x: any, context: any = x): Item {
  return {
    step: _atd_read_required_field('Item', 'step', _atd_read_int, x['step'], x),
    kind: _atd_read_required_field('Item', 'kind', _atd_read_array(readKind), x['kind'], x),
    goal_id: _atd_read_required_field('Item', 'goal_id', _atd_read_int, x['goal_id'], x),
    runtime_id: _atd_read_required_field('Item', 'runtime_id', _atd_read_int, x['runtime_id'], x),
    name: _atd_read_required_field('Item', 'name', _atd_read_string, x['name'], x),
    payload: _atd_read_required_field('Item', 'payload', _atd_read_array(_atd_read_string), x['payload'], x),
  };
}

export function writeKind(x: Kind, context: any = x): any {
  switch (x.kind) {
    case 'Start':
      return 'Start'
    case 'Info':
      return 'Info'
    case 'Stop':
      return ['Stop', writeStop(x.value, x)]
    case 'Meta':
      return 'Meta'
  }
}

export function readKind(x: any, context: any = x): Kind {
  if (typeof x === 'string') {
    switch (x) {
      case 'Start':
        return { kind: 'Start' }
      case 'Info':
        return { kind: 'Info' }
      case 'Meta':
        return { kind: 'Meta' }
      default:
        _atd_bad_json('Kind', x, context)
        throw new Error('impossible')
    }
  }
  else {
    _atd_check_json_tuple(2, x, context)
    switch (x[0]) {
      case 'Stop':
        return { kind: 'Stop', value: readStop(x[1], x) }
      default:
        _atd_bad_json('Kind', x, context)
        throw new Error('impossible')
    }
  }
}

export function writeStop(x: Stop, context: any = x): any {
  return {
    'cause': _atd_write_required_field('Stop', 'cause', _atd_write_string, x.cause, x),
    'time': _atd_write_required_field('Stop', 'time', _atd_write_float, x.time, x),
  };
}

export function readStop(x: any, context: any = x): Stop {
  return {
    cause: _atd_read_required_field('Stop', 'cause', _atd_read_string, x['cause'], x),
    time: _atd_read_required_field('Stop', 'time', _atd_read_float, x['time'], x),
  };
}

export function writeRawTrace(x: RawTrace, context: any = x): any {
  return _atd_write_array(writeItem)(x, context);
}

export function readRawTrace(x: any, context: any = x): RawTrace {
  return _atd_read_array(readItem)(x, context);
}


/////////////////////////////////////////////////////////////////////
// Runtime library
/////////////////////////////////////////////////////////////////////

function _atd_missing_json_field(type_name: string, json_field_name: string) {
    throw new Error(`missing field '${json_field_name}'` +
                    ` in JSON object of type '${type_name}'`)
}

function _atd_missing_ts_field(type_name: string, ts_field_name: string) {
    throw new Error(`missing field '${ts_field_name}'` +
                    ` in TypeScript object of type '${type_name}'`)
}

function _atd_bad_json(expected_type: string, json_value: any, context: any) {
  let value_str = JSON.stringify(json_value)
  if (value_str.length > 200)
    value_str = value_str.substring(0, 200) + '…';

  throw new Error(`incompatible JSON value where` +
                  ` type '${expected_type}' was expected: '${value_str}'.` +
                  ` Occurs in '${JSON.stringify(context)}'.`)
}

function _atd_bad_ts(expected_type: string, ts_value: any, context: any) {
  let value_str = JSON.stringify(ts_value)
  if (value_str.length > 200)
    value_str = value_str.substring(0, 200) + '…';

  throw new Error(`incompatible TypeScript value where` +
                  ` type '${expected_type}' was expected: '${value_str}'.` +
                  ` Occurs in '${JSON.stringify(context)}'.`)
}

function _atd_check_json_tuple(len: number /*int*/, x: any, context: any) {
  if (! Array.isArray(x) || x.length !== len)
    _atd_bad_json('tuple of length ' + len, x, context);
}

function _atd_read_int(x: any, context: any): number /*int*/ {
  if (Number.isInteger(x))
    return x
  else {
    _atd_bad_json('integer', x, context)
    throw new Error('impossible')
  }
}

function _atd_read_float(x: any, context: any): number {
  if (isFinite(x))
    return x
  else {
    _atd_bad_json('number', x, context)
    throw new Error('impossible')
  }
}

function _atd_read_string(x: any, context: any): string {
  if (typeof x === 'string')
    return x
  else {
    _atd_bad_json('string', x, context)
    throw new Error('impossible')
  }
}

function _atd_read_required_field<T>(type_name: string,
                                     field_name: string,
                                     read_elt: (x: any, context: any) => T,
                                     x: any,
                                     context: any): T {
  if (x === undefined) {
    _atd_missing_json_field(type_name, field_name)
    throw new Error('impossible')
  }
  else
    return read_elt(x, context)
}

function _atd_read_array<T>(read_elt: (x: any, context: any) => T):
  (elts: any, context: any) => T[] {
  function read_array(elts: any, context: any): T[] {
    if (Array.isArray(elts))
      return elts.map((x) => read_elt(x, elts))
    else {
      _atd_bad_json('array', elts, context)
      throw new Error('impossible')
    }
  }
  return read_array
}

function _atd_write_int(x: any, context: any): number /*int*/ {
  if (Number.isInteger(x))
    return x
  else {
    _atd_bad_ts('integer', x, context)
    throw new Error('impossible')
  }
}

function _atd_write_float(x: any, context: any): number {
  if (isFinite(x))
    return x
  else {
    _atd_bad_ts('number', x, context)
    throw new Error('impossible')
  }
}

function _atd_write_string(x: any, context: any): string {
  if (typeof x === 'string')
    return x
  else {
    _atd_bad_ts('string', x, context)
    throw new Error('impossible')
  }
}

function _atd_write_array<T>(write_elt: (elt: T, context: any) => any):
  (elts: T[], context: any) => any {
  return ((elts: T[], context: any): any =>
    elts.map((x) => write_elt(x, elts))
  )
}

function _atd_write_required_field<T>(type_name: string,
                                      field_name: string,
                                      write_elt: (x: T, context: any) => any,
                                      x: T,
                                      context: any): any {
  if (x === undefined) {
    _atd_missing_ts_field(type_name, field_name)
    throw new Error('impossible')
  }
  else
    return write_elt(x, context)
}

